export declare class MillenniumMonth {
    static readonly JANUARY: MillenniumMonth;
    static readonly FEBRUARY: MillenniumMonth;
    static readonly MARCH: MillenniumMonth;
    static readonly APRIL: MillenniumMonth;
    static readonly MAY: MillenniumMonth;
    static readonly JUNE: MillenniumMonth;
    static readonly JULY: MillenniumMonth;
    static readonly AUGUST: MillenniumMonth;
    static readonly SEPTEMBER: MillenniumMonth;
    static readonly NOVEMBER: MillenniumMonth;
    static readonly OCTOBER: MillenniumMonth;
    static readonly DECEMBER: MillenniumMonth;
    private static monthNumberMap;
    private static monthNameMap;
    private monthNumber;
    private monthName;
    private daysInMonth;
    private constructor();
    private static addMonthNumberMapping;
    private static addMonthNameMapping;
    static getMonthByName(monthName: string): MillenniumMonth;
    static getMonthByNumber(monthNumber: number): MillenniumMonth;
    static getMonthByNumberZeroIndexed(monthNumber: number): MillenniumMonth;
    static getMonthByDayInYear(day: number, year: number): MillenniumMonth | undefined;
    static getRelativeMonth(relativeIndex: number): MillenniumMonth;
    static thisMonth(): MillenniumMonth;
    static lastMonth(): MillenniumMonth;
    static nextMonth(): MillenniumMonth;
    getRelativeMonth(relativeIndex: number): MillenniumMonth;
    lastMonth(): MillenniumMonth;
    nextMonth(): MillenniumMonth;
    getMonthNumber(): number;
    getMonthNumberZeroIndexed(): number;
    getMonthName(): string;
    getDaysInMonth(year: number): number;
    getDaysSinceBeginningOfYear(year: number): number;
    toString(): string;
}
