export declare class MillenniumTimeZone {
    static readonly UTC_POS_14: MillenniumTimeZone;
    static readonly UTC_POS_13_75: MillenniumTimeZone;
    static readonly UTC_POS_13: MillenniumTimeZone;
    static readonly UTC_POS_12_75: MillenniumTimeZone;
    static readonly UTC_POS_12: MillenniumTimeZone;
    static readonly UTC_POS_11: MillenniumTimeZone;
    static readonly UTC_POS_10: MillenniumTimeZone;
    static readonly UTC_POS_9: MillenniumTimeZone;
    static readonly UTC_POS_8: MillenniumTimeZone;
    static readonly UTC_POS_7: MillenniumTimeZone;
    static readonly UTC_POS_6: MillenniumTimeZone;
    static readonly UTC_POS_5: MillenniumTimeZone;
    static readonly UTC_POS_4: MillenniumTimeZone;
    static readonly UTC_POS_3: MillenniumTimeZone;
    static readonly UTC_POS_2: MillenniumTimeZone;
    static readonly UTC_POS_1: MillenniumTimeZone;
    static readonly UTC: MillenniumTimeZone;
    static readonly UTC_NEG_1: MillenniumTimeZone;
    static readonly UTC_NEG_2: MillenniumTimeZone;
    static readonly UTC_NEG_2_5: MillenniumTimeZone;
    static readonly UTC_NEG_3: MillenniumTimeZone;
    static readonly UTC_NEG_3_5: MillenniumTimeZone;
    static readonly UTC_NEG_4: MillenniumTimeZone;
    static readonly UTC_NEG_5: MillenniumTimeZone;
    static readonly UTC_NEG_6: MillenniumTimeZone;
    static readonly UTC_NEG_7: MillenniumTimeZone;
    static readonly UTC_NEG_8: MillenniumTimeZone;
    static readonly UTC_NEG_9: MillenniumTimeZone;
    static readonly UTC_NEG_9_5: MillenniumTimeZone;
    static readonly UTC_NEG_10: MillenniumTimeZone;
    static readonly UTC_NEG_11: MillenniumTimeZone;
    static readonly UTC_NEG_12: MillenniumTimeZone;
    private offset;
    private names;
    private static offsetMap;
    private constructor();
    private static addOffsetMapping;
    static getTimezoneForOffset(offset: number): MillenniumTimeZone | undefined;
    getOffset(): number;
    getPrimaryName(): string;
    getAllNames(): string[];
}
